[workspace]
members = ["libs/veter-host", "libs/vge-render", "libs/vge-ui", "protocol/prt", "protocol/ses", "protocol/vft", "protocol/vge", "protocol/vss", "tools/breakout", "tools/spinner", "tools/vcat", "tools/vdraw", "tools/vfm", "tools/vft-client", "tools/vmux", "tools/vproto", "tools/vplay", "tools/vrecv", "tools/vsd", "tools/vsend", "tools/vssh", "vendored/femtovg", "vendored/vt100", "veter"]
resolver = "2"
